name: Draft release

on:
  push:
    branches:
      - master

jobs:
  prepare_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create release draft'
        id: release_draft
        uses: release-drafter/release-drafter@v5.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
